# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c0582cf35f284561677506aac20c26beef22381fc1f60b11fa8c68f32a2a984025bc95b03d98cec7245dc138dc94f07af6a46953a00077493c1c2c6eb2abbec

test:
  secret_key_base: 4ef6f06fe2c016d13118308eba377fd81314087abf45b4b72675be812e629620c946c16f7a078f7e45d26a59ffbb42ffb38250cae6f823721681dff63b4525a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
